### ISSUE TITLE
Incorrect timestamp values?

### ISSUE THREAD

**Issue by moustacheful** [cloudflare/GCS-To-Big-Query#6]
Currently both the timestamps being inserted to BQ seem to be wrong, i'm getting timestamps such as 
`11476-03-23 23:22:37..347 UTC`.

The data in the bucket looks like this:

```
{
...
"EdgeStartTimestamp":1529014095948999936
}
```

Out of the box I can't seem to use the Cloudflare Log Analysis template (https://datastudio.google.com/u/0/reporting/1ez3m7Yf8AZLfM6aYRjfgF0pPpRvOwhTh/page/mAzI) 
I've tried setting these fields as INTEGER but as it seems to be forcing an external schema it just doesn't do anything.

We do have an older instance of the same script running that seems to work just fine.

**Comment by shagamemnon** [comment]
@moustacheful Thanks for opening this issue. We've started applying the new timestamp data type to all Logpush customers. The old script was incompatible with our WAF events and a number of newer fields due to type coercion.

You can override the external schema by editing line 46 in `index.js` to look like this:
```javascript
// ...
_schema = backupSchema
```

I'll keep this issue open for the time being while we consider how to version this. Thanks!
